# Site settings
title: note book!
email: va6un.b@gmail.com
description: Personal Blog!!!
url: https://va6un.github.io
author: Varun Bhuvanendran
footer: va6un.github.com

# Build settings
markdown: kramdown
permalink: /:categories/:title/
highlighter: rouge
