# Command
# export GEM_HOME=$HOME/gems
# jekyll serve

# Site settings
title: va6un.github.io
email: va6un.b@gmail.com
description: Blog!!!
url: https://va6un.github.io
author: Varun Bhuvanendran

# Build settings
markdown: kramdown
permalink: /:title

# Defaults settings
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      author: Varun Bhuvanendran
      layout: "post"