# Site settings
title: va6un.github.io
description: Blog!
url: https://va6un.github.io
author: Varun Bhuvanendran


# Build settings
markdown: kramdown
permalink: /:categories/:title/
highlighter: rouge
